repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements
    - id: mixed-line-ending
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.7
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.394
  hooks:
    - id: pyright
      name: pyright (system)
      description: 'pyright static type checker'
      entry: pyright
      language: system
      'types_or': [python, pyi]
      require_serial: true
      minimum_pre_commit_version: '2.9.2'
