name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        run: uv sync --all-extras --dev

      - name: Check linting
        run: uv run ruff check

      - name: Check pyright
        run: uv run pyright .
