name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        run: |
          pip install -U pip
          pip install -e .[lint,scripts,test,check]


      - name: Check linting
        run: inv lintall

      - name: Check pyright
        run: inv check-pyright
